// Mocks generated by Mockito 5.4.5 from annotations
// in web3_smartwatch_sdk/test/web3_smartwatch_sdk_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:built_value/serializer.dart' as _i3;
import 'package:dio/dio.dart' as _i2;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:openapi/openapi.dart' as _i8;
import 'package:openapi/src/api/user_api.dart' as _i4;
import 'package:openapi/src/model/api_search_address_address_get200_response.dart'
    as _i9;
import 'package:openapi/src/model/api_search_did_did_get200_response.dart'
    as _i10;
import 'package:openapi/src/model/api_user_address_balance_get200_response.dart'
    as _i11;
import 'package:openapi/src/model/api_user_address_get200_response.dart'
    as _i12;
import 'package:openapi/src/model/api_user_address_nfts_get200_response.dart'
    as _i13;
import 'package:web3_smartwatch_sdk/src/interface.dart' as _i5;
import 'package:web3_smartwatch_sdk/src/web3_smartwatch_sdk.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSerializers_1 extends _i1.SmartFake implements _i3.Serializers {
  _FakeSerializers_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserApi_2 extends _i1.SmartFake implements _i4.UserApi {
  _FakeUserApi_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_3<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBalance_4 extends _i1.SmartFake implements _i5.Balance {
  _FakeBalance_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCreateWalletResponse_5 extends _i1.SmartFake
    implements _i5.CreateWalletResponse {
  _FakeCreateWalletResponse_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FlutterSecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSecureStorage extends _i1.Mock
    implements _i6.FlutterSecureStorage {
  @override
  _i7.Future<void> write({
    required String? key,
    required String? value,
    _i6.IOSOptions? iOptions = _i6.IOSOptions.defaultOptions,
    _i6.AndroidOptions? aOptions,
    _i6.LinuxOptions? lOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#write, [], {
              #key: key,
              #value: value,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<String?> read({
    required String? key,
    _i6.IOSOptions? iOptions = _i6.IOSOptions.defaultOptions,
    _i6.AndroidOptions? aOptions,
    _i6.LinuxOptions? lOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#read, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
            }),
            returnValue: _i7.Future<String?>.value(),
            returnValueForMissingStub: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<bool> containsKey({
    required String? key,
    _i6.IOSOptions? iOptions = _i6.IOSOptions.defaultOptions,
    _i6.AndroidOptions? aOptions,
    _i6.LinuxOptions? lOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
            }),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<void> delete({
    required String? key,
    _i6.IOSOptions? iOptions = _i6.IOSOptions.defaultOptions,
    _i6.AndroidOptions? aOptions,
    _i6.LinuxOptions? lOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<Map<String, String>> readAll({
    _i6.IOSOptions? iOptions = _i6.IOSOptions.defaultOptions,
    _i6.AndroidOptions? aOptions,
    _i6.LinuxOptions? lOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
            }),
            returnValue: _i7.Future<Map<String, String>>.value(
              <String, String>{},
            ),
            returnValueForMissingStub: _i7.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i7.Future<Map<String, String>>);

  @override
  _i7.Future<void> deleteAll({
    _i6.IOSOptions? iOptions = _i6.IOSOptions.defaultOptions,
    _i6.AndroidOptions? aOptions,
    _i6.LinuxOptions? lOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [Openapi].
///
/// See the documentation for Mockito's code generation for more information.
class MockOpenapi extends _i1.Mock implements _i8.Openapi {
  @override
  _i2.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_0(this, Invocation.getter(#dio)),
            returnValueForMissingStub: _FakeDio_0(
              this,
              Invocation.getter(#dio),
            ),
          )
          as _i2.Dio);

  @override
  _i3.Serializers get serializers =>
      (super.noSuchMethod(
            Invocation.getter(#serializers),
            returnValue: _FakeSerializers_1(
              this,
              Invocation.getter(#serializers),
            ),
            returnValueForMissingStub: _FakeSerializers_1(
              this,
              Invocation.getter(#serializers),
            ),
          )
          as _i3.Serializers);

  @override
  void setOAuthToken(String? name, String? token) => super.noSuchMethod(
    Invocation.method(#setOAuthToken, [name, token]),
    returnValueForMissingStub: null,
  );

  @override
  void setBearerAuth(String? name, String? token) => super.noSuchMethod(
    Invocation.method(#setBearerAuth, [name, token]),
    returnValueForMissingStub: null,
  );

  @override
  void setBasicAuth(String? name, String? username, String? password) =>
      super.noSuchMethod(
        Invocation.method(#setBasicAuth, [name, username, password]),
        returnValueForMissingStub: null,
      );

  @override
  void setApiKey(String? name, String? apiKey) => super.noSuchMethod(
    Invocation.method(#setApiKey, [name, apiKey]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.UserApi getUserApi() =>
      (super.noSuchMethod(
            Invocation.method(#getUserApi, []),
            returnValue: _FakeUserApi_2(
              this,
              Invocation.method(#getUserApi, []),
            ),
            returnValueForMissingStub: _FakeUserApi_2(
              this,
              Invocation.method(#getUserApi, []),
            ),
          )
          as _i4.UserApi);
}

/// A class which mocks [UserApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserApi extends _i1.Mock implements _i4.UserApi {
  @override
  _i7.Future<_i2.Response<_i9.ApiSearchAddressAddressGet200Response>>
  apiSearchAddressAddressGet({
    required String? address,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#apiSearchAddressAddressGet, [], {
              #address: address,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i7.Future<
              _i2.Response<_i9.ApiSearchAddressAddressGet200Response>
            >.value(
              _FakeResponse_3<_i9.ApiSearchAddressAddressGet200Response>(
                this,
                Invocation.method(#apiSearchAddressAddressGet, [], {
                  #address: address,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
            returnValueForMissingStub: _i7.Future<
              _i2.Response<_i9.ApiSearchAddressAddressGet200Response>
            >.value(
              _FakeResponse_3<_i9.ApiSearchAddressAddressGet200Response>(
                this,
                Invocation.method(#apiSearchAddressAddressGet, [], {
                  #address: address,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i7.Future<
            _i2.Response<_i9.ApiSearchAddressAddressGet200Response>
          >);

  @override
  _i7.Future<_i2.Response<_i10.ApiSearchDidDidGet200Response>>
  apiSearchDidDidGet({
    required String? did,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#apiSearchDidDidGet, [], {
              #did: did,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i7.Future<
              _i2.Response<_i10.ApiSearchDidDidGet200Response>
            >.value(
              _FakeResponse_3<_i10.ApiSearchDidDidGet200Response>(
                this,
                Invocation.method(#apiSearchDidDidGet, [], {
                  #did: did,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
            returnValueForMissingStub: _i7.Future<
              _i2.Response<_i10.ApiSearchDidDidGet200Response>
            >.value(
              _FakeResponse_3<_i10.ApiSearchDidDidGet200Response>(
                this,
                Invocation.method(#apiSearchDidDidGet, [], {
                  #did: did,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i7.Future<_i2.Response<_i10.ApiSearchDidDidGet200Response>>);

  @override
  _i7.Future<_i2.Response<_i11.ApiUserAddressBalanceGet200Response>>
  apiUserAddressBalanceGet({
    required String? address,
    String? tokenAddresses,
    bool? includeZeroBalance = false,
    String? pageToken,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#apiUserAddressBalanceGet, [], {
              #address: address,
              #tokenAddresses: tokenAddresses,
              #includeZeroBalance: includeZeroBalance,
              #pageToken: pageToken,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i7.Future<
              _i2.Response<_i11.ApiUserAddressBalanceGet200Response>
            >.value(
              _FakeResponse_3<_i11.ApiUserAddressBalanceGet200Response>(
                this,
                Invocation.method(#apiUserAddressBalanceGet, [], {
                  #address: address,
                  #tokenAddresses: tokenAddresses,
                  #includeZeroBalance: includeZeroBalance,
                  #pageToken: pageToken,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
            returnValueForMissingStub: _i7.Future<
              _i2.Response<_i11.ApiUserAddressBalanceGet200Response>
            >.value(
              _FakeResponse_3<_i11.ApiUserAddressBalanceGet200Response>(
                this,
                Invocation.method(#apiUserAddressBalanceGet, [], {
                  #address: address,
                  #tokenAddresses: tokenAddresses,
                  #includeZeroBalance: includeZeroBalance,
                  #pageToken: pageToken,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i7.Future<
            _i2.Response<_i11.ApiUserAddressBalanceGet200Response>
          >);

  @override
  _i7.Future<_i2.Response<_i12.ApiUserAddressGet200Response>>
  apiUserAddressGet({
    required String? address,
    bool? includeZeroBalance = false,
    String? pageToken,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#apiUserAddressGet, [], {
              #address: address,
              #includeZeroBalance: includeZeroBalance,
              #pageToken: pageToken,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i7.Future<
              _i2.Response<_i12.ApiUserAddressGet200Response>
            >.value(
              _FakeResponse_3<_i12.ApiUserAddressGet200Response>(
                this,
                Invocation.method(#apiUserAddressGet, [], {
                  #address: address,
                  #includeZeroBalance: includeZeroBalance,
                  #pageToken: pageToken,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
            returnValueForMissingStub: _i7.Future<
              _i2.Response<_i12.ApiUserAddressGet200Response>
            >.value(
              _FakeResponse_3<_i12.ApiUserAddressGet200Response>(
                this,
                Invocation.method(#apiUserAddressGet, [], {
                  #address: address,
                  #includeZeroBalance: includeZeroBalance,
                  #pageToken: pageToken,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i7.Future<_i2.Response<_i12.ApiUserAddressGet200Response>>);

  @override
  _i7.Future<_i2.Response<_i13.ApiUserAddressNftsGet200Response>>
  apiUserAddressNftsGet({
    required String? address,
    bool? includeMetadata = true,
    String? pageToken,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#apiUserAddressNftsGet, [], {
              #address: address,
              #includeMetadata: includeMetadata,
              #pageToken: pageToken,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i7.Future<
              _i2.Response<_i13.ApiUserAddressNftsGet200Response>
            >.value(
              _FakeResponse_3<_i13.ApiUserAddressNftsGet200Response>(
                this,
                Invocation.method(#apiUserAddressNftsGet, [], {
                  #address: address,
                  #includeMetadata: includeMetadata,
                  #pageToken: pageToken,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
            returnValueForMissingStub: _i7.Future<
              _i2.Response<_i13.ApiUserAddressNftsGet200Response>
            >.value(
              _FakeResponse_3<_i13.ApiUserAddressNftsGet200Response>(
                this,
                Invocation.method(#apiUserAddressNftsGet, [], {
                  #address: address,
                  #includeMetadata: includeMetadata,
                  #pageToken: pageToken,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i7.Future<_i2.Response<_i13.ApiUserAddressNftsGet200Response>>);
}

/// A class which mocks [Web3SmartwatchSdk].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeb3SmartwatchSdk extends _i1.Mock implements _i14.Web3SmartwatchSdk {
  @override
  _i2.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_0(this, Invocation.getter(#dio)),
            returnValueForMissingStub: _FakeDio_0(
              this,
              Invocation.getter(#dio),
            ),
          )
          as _i2.Dio);

  @override
  _i3.Serializers get serializers =>
      (super.noSuchMethod(
            Invocation.getter(#serializers),
            returnValue: _FakeSerializers_1(
              this,
              Invocation.getter(#serializers),
            ),
            returnValueForMissingStub: _FakeSerializers_1(
              this,
              Invocation.getter(#serializers),
            ),
          )
          as _i3.Serializers);

  @override
  void setCurrentWalletAddress(String? address) => super.noSuchMethod(
    Invocation.method(#setCurrentWalletAddress, [address]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<_i5.Balance> getAddressBalance(String? address) =>
      (super.noSuchMethod(
            Invocation.method(#getAddressBalance, [address]),
            returnValue: _i7.Future<_i5.Balance>.value(
              _FakeBalance_4(
                this,
                Invocation.method(#getAddressBalance, [address]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i5.Balance>.value(
              _FakeBalance_4(
                this,
                Invocation.method(#getAddressBalance, [address]),
              ),
            ),
          )
          as _i7.Future<_i5.Balance>);

  @override
  _i7.Future<_i5.Balance?> getAddressBalanceByToken(
    String? address,
    String? contractAddress,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAddressBalanceByToken, [
              address,
              contractAddress,
            ]),
            returnValue: _i7.Future<_i5.Balance?>.value(),
            returnValueForMissingStub: _i7.Future<_i5.Balance?>.value(),
          )
          as _i7.Future<_i5.Balance?>);

  @override
  _i7.Future<_i5.CreateWalletResponse> createWallet({String? did}) =>
      (super.noSuchMethod(
            Invocation.method(#createWallet, [], {#did: did}),
            returnValue: _i7.Future<_i5.CreateWalletResponse>.value(
              _FakeCreateWalletResponse_5(
                this,
                Invocation.method(#createWallet, [], {#did: did}),
              ),
            ),
            returnValueForMissingStub:
                _i7.Future<_i5.CreateWalletResponse>.value(
                  _FakeCreateWalletResponse_5(
                    this,
                    Invocation.method(#createWallet, [], {#did: did}),
                  ),
                ),
          )
          as _i7.Future<_i5.CreateWalletResponse>);

  @override
  _i7.Future<_i5.Wallet?> getWallet() =>
      (super.noSuchMethod(
            Invocation.method(#getWallet, []),
            returnValue: _i7.Future<_i5.Wallet?>.value(),
            returnValueForMissingStub: _i7.Future<_i5.Wallet?>.value(),
          )
          as _i7.Future<_i5.Wallet?>);

  @override
  void setOAuthToken(String? name, String? token) => super.noSuchMethod(
    Invocation.method(#setOAuthToken, [name, token]),
    returnValueForMissingStub: null,
  );

  @override
  void setBearerAuth(String? name, String? token) => super.noSuchMethod(
    Invocation.method(#setBearerAuth, [name, token]),
    returnValueForMissingStub: null,
  );

  @override
  void setBasicAuth(String? name, String? username, String? password) =>
      super.noSuchMethod(
        Invocation.method(#setBasicAuth, [name, username, password]),
        returnValueForMissingStub: null,
      );

  @override
  void setApiKey(String? name, String? apiKey) => super.noSuchMethod(
    Invocation.method(#setApiKey, [name, apiKey]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.UserApi getUserApi() =>
      (super.noSuchMethod(
            Invocation.method(#getUserApi, []),
            returnValue: _FakeUserApi_2(
              this,
              Invocation.method(#getUserApi, []),
            ),
            returnValueForMissingStub: _FakeUserApi_2(
              this,
              Invocation.method(#getUserApi, []),
            ),
          )
          as _i4.UserApi);
}
