name: web3_smartwatch_sdk
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

# Add regular dependencies here.
dependencies:
  openapi_generator_annotations: ^6.1.0
  openapi:
    path: ./api/web3-smartwatch-client
  web3dart: ^2.7.3
  bip39: ^1.0.6
  flutter_secure_storage: ^4.2.1
  bip32: ^2.0.0
  retry: ^3.1.2
  mockito: ^5.4.5

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  flutter_test:
    sdk: flutter
  openapi_generator: ^6.1.0
  build_runner: ^2.4.15
  http_mock_adapter: ^0.6.1
